-- MySQL Script generated by MySQL Workbench
-- Sat Nov  3 02:59:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sygeto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sygeto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sygeto` DEFAULT CHARACTER SET utf8 ;
USE `sygeto` ;

-- -----------------------------------------------------
-- Table `sygeto`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`clients` (
  `cliid` INT(11) NOT NULL AUTO_INCREMENT,
  `clinom` VARCHAR(255) NOT NULL,
  `cliprenom` VARCHAR(150) NOT NULL,
  `clitelephone` VARCHAR(50) NOT NULL,
  `cliportable` VARCHAR(50) NOT NULL,
  `cliville` VARCHAR(255) NOT NULL,
  `clirealiserpar` INT(11) NOT NULL,
  `clidatecreation` DATETIME NOT NULL,
  PRIMARY KEY (`cliid`),
  INDEX `clirealiserpar` (`clirealiserpar` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`fournisseurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`fournisseurs` (
  `fouid` INT(11) NOT NULL AUTO_INCREMENT,
  `founom` VARCHAR(150) NULL DEFAULT NULL,
  `fouprenom` VARCHAR(45) NULL DEFAULT NULL,
  `foutelephone` VARCHAR(45) NULL DEFAULT NULL,
  `fouportable` VARCHAR(45) NULL DEFAULT NULL,
  `fouville` VARCHAR(155) NULL DEFAULT NULL,
  `fourealiserpar` INT(11) NOT NULL,
  `foudatecreation` DATETIME NOT NULL,
  PRIMARY KEY (`fouid`),
  INDEX `fourealiserpar` (`fourealiserpar` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`paiement` (
  `paiid` INT(11) NOT NULL AUTO_INCREMENT,
  `pailibelle` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`paiid`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`employes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`employes` (
  `empid` INT(11) NOT NULL AUTO_INCREMENT,
  `empnom` VARCHAR(150) NULL DEFAULT NULL,
  `empprenom` VARCHAR(150) NULL DEFAULT NULL,
  `emptelephone` VARCHAR(45) NULL DEFAULT NULL,
  `empportable` VARCHAR(255) NULL DEFAULT NULL,
  `empsexe` INT(11) NULL DEFAULT NULL,
  `empresidence` VARCHAR(155) NULL DEFAULT NULL,
  `empcni` VARCHAR(45) NULL DEFAULT NULL,
  `emprealiserpar` INT(11) NOT NULL,
  `empdatecreatioin` DATETIME NOT NULL,
  PRIMARY KEY (`empid`),
  INDEX `emprealiserpar` (`emprealiserpar` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`profile` (
  `prfid` INT(11) NOT NULL AUTO_INCREMENT,
  `prflibelle` VARCHAR(45) NULL DEFAULT NULL,
  `prfdroitacces` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`prfid`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`users` (
  `useid` INT(11) NOT NULL AUTO_INCREMENT,
  `uselogin` VARCHAR(45) NULL DEFAULT NULL,
  `usemdp` TEXT NULL DEFAULT NULL,
  `usephoto` TEXT NULL DEFAULT NULL,
  `useemployer` INT(11) NOT NULL,
  `usedroits` TEXT NULL DEFAULT NULL,
  `usedatecreation` VARCHAR(45) NULL DEFAULT NULL,
  `useprofile` INT(11) NOT NULL,
  PRIMARY KEY (`useid`),
  INDEX `fk_user_employers1_idx` (`useemployer` ASC),
  INDEX `fk_users_profile1_idx` (`useprofile` ASC),
  CONSTRAINT `fk_user_employers1`
    FOREIGN KEY (`useemployer`)
    REFERENCES `sygeto`.`employes` (`empid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_profile1`
    FOREIGN KEY (`useprofile`)
    REFERENCES `sygeto`.`profile` (`prfid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`offres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`offres` (
  `offid` INT(11) NOT NULL AUTO_INCREMENT,
  `offdate` DATETIME NOT NULL,
  `offdescription` VARCHAR(45) NULL DEFAULT NULL,
  `offvalidite` INT(11) NOT NULL DEFAULT '0',
  `offpayement` INT(11) NULL DEFAULT NULL,
  `offfournisseur` INT(11) NULL DEFAULT NULL,
  `offrealiserpar` INT(11) NOT NULL,
  PRIMARY KEY (`offid`),
  INDEX `fk_commandeExt_payement1_idx` (`offpayement` ASC),
  INDEX `fk_commandeExt_fournisseurs1_idx` (`offfournisseur` ASC),
  INDEX `fk_commandeExt_user1_idx` (`offrealiserpar` ASC),
  CONSTRAINT `fk_commandeExt_fournisseurs1`
    FOREIGN KEY (`offfournisseur`)
    REFERENCES `sygeto`.`fournisseurs` (`fouid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commandeExt_payement1`
    FOREIGN KEY (`offpayement`)
    REFERENCES `sygeto`.`paiement` (`paiid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commandeExt_user1`
    FOREIGN KEY (`offrealiserpar`)
    REFERENCES `sygeto`.`users` (`useid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`commandes` (
  `cmdid` INT(11) NOT NULL AUTO_INCREMENT,
  `cmddescription` TEXT NULL DEFAULT NULL,
  `cmdpaiement` INT(11) NOT NULL,
  `cmdrealiserpar` INT(11) NOT NULL,
  `cmddate` DATETIME NULL DEFAULT NULL,
  `cmdclient` INT(11) NOT NULL,
  PRIMARY KEY (`cmdid`),
  INDEX `fk_commandes_payement1_idx` (`cmdpaiement` ASC),
  INDEX `fk_commandes_user1_idx` (`cmdrealiserpar` ASC),
  INDEX `fk_commandes_clients1_idx` (`cmdclient` ASC),
  CONSTRAINT `fk_commandes_payement1`
    FOREIGN KEY (`cmdpaiement`)
    REFERENCES `sygeto`.`paiement` (`paiid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commandes_user1`
    FOREIGN KEY (`cmdrealiserpar`)
    REFERENCES `sygeto`.`users` (`useid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commandes_clients1`
    FOREIGN KEY (`cmdclient`)
    REFERENCES `sygeto`.`clients` (`cliid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`connexions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`connexions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `datedebut` DATETIME NOT NULL,
  `ipsource` VARCHAR(255) NOT NULL,
  `machinesource` VARCHAR(255) NOT NULL,
  `connexion` VARCHAR(255) NOT NULL,
  `datefin` DATETIME NULL DEFAULT NULL,
  `deconnexion` VARCHAR(255) NOT NULL,
  `user` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_connexions_users1_idx` (`user` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`familles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`familles` (
  `famid` INT(11) NOT NULL AUTO_INCREMENT,
  `famlibelle` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`famid`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`groupemenu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`groupemenu` (
  `grpid` INT(11) NOT NULL AUTO_INCREMENT,
  `grplibelle` VARCHAR(255) NOT NULL,
  `grpicone` TEXT NOT NULL,
  `url` TEXT NOT NULL,
  `grporder` INT(11) NOT NULL,
  PRIMARY KEY (`grpid`))
ENGINE = MyISAM
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`menus` (
  `menid` INT(11) NOT NULL AUTO_INCREMENT,
  `menlibelle` VARCHAR(255) NOT NULL,
  `menhref` TEXT NOT NULL,
  `menicone` TEXT NOT NULL,
  `mengroupe` INT(11) NOT NULL,
  `menrole` INT(11) NOT NULL,
  PRIMARY KEY (`menid`),
  INDEX `fk_menus_groupemenu1_idx` (`mengroupe` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`unitemesure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`unitemesure` (
  `uniid` INT(11) NOT NULL AUTO_INCREMENT,
  `unilibelle` VARCHAR(45) NOT NULL,
  `uniabv` VARCHAR(10) NOT NULL,
  `unirealiserpar` INT(11) NOT NULL,
  `unidatecreation` DATETIME NOT NULL,
  PRIMARY KEY (`uniid`),
  INDEX `unirealiserpar` (`unirealiserpar` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`produits` (
  `proid` INT(11) NOT NULL AUTO_INCREMENT,
  `prodesignation` VARCHAR(150) NOT NULL,
  `proprixUnitAchat` VARCHAR(45) NOT NULL,
  `proprixUnitVente` VARCHAR(45) NULL DEFAULT NULL,
  `proreference` TEXT NULL DEFAULT NULL,
  `prodatePeremption` DATE NOT NULL,
  `datecreation` DATE NULL DEFAULT NULL,
  `promarque` INT(11) NULL DEFAULT NULL,
  `profamille` INT(11) NOT NULL,
  `proprixblogVente` FLOAT NULL DEFAULT NULL COMMENT 'prix de vente en gro d\'un produit par exemple le prix d\'un sac de riz, le prix d\'un carton de savon , prix d\'une plalette d\'eau',
  `pronbproduitBlog` FLOAT NULL DEFAULT NULL COMMENT 'd\'un nombre d\'un produit que peut contenir son blog, par exemple le nombre de boite de sandrine dans son carton, le nombre de kilo de riz pour un sac de riz, le nombre de bouteille dans une plalette',
  `prounitemessure` INT(11) NULL DEFAULT NULL,
  `proseuilalert` INT(11) NULL DEFAULT '5',
  `profournisseur` INT(11) NOT NULL,
  `prorealiserpar` INT(11) NOT NULL,
  `prodatecreation` DATETIME NOT NULL,
  PRIMARY KEY (`proid`),
  INDEX `fk_produits_unitemesure1_idx` (`prounitemessure` ASC),
  INDEX `profamille` (`profamille` ASC),
  INDEX `prorealiserpar` (`prorealiserpar` ASC),
  CONSTRAINT `fk_produit_famille1`
    FOREIGN KEY (`profamille`)
    REFERENCES `sygeto`.`familles` (`famid`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_produits_unitemesure1`
    FOREIGN KEY (`prounitemessure`)
    REFERENCES `sygeto`.`unitemesure` (`uniid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`mouvements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`mouvements` (
  `mvtid` INT(11) NOT NULL AUTO_INCREMENT,
  `mvtdate` DATETIME NULL DEFAULT NULL,
  `mvtquantite` FLOAT NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `mvtproduit` INT(11) NULL DEFAULT NULL,
  `mvttype` INT(11) NULL DEFAULT NULL COMMENT '0 si on effectue une sortie et 1 si on effetue un entrée',
  `mvtrealiserpar` INT(11) NOT NULL,
  PRIMARY KEY (`mvtid`),
  INDEX `fk_movementBoutique_produits1_idx` (`mvtproduit` ASC),
  INDEX `fk_mouvements_users1_idx` (`mvtrealiserpar` ASC),
  CONSTRAINT `fk_movementBoutique_produits1`
    FOREIGN KEY (`mvtproduit`)
    REFERENCES `sygeto`.`produits` (`proid`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mouvements_users1`
    FOREIGN KEY (`mvtrealiserpar`)
    REFERENCES `sygeto`.`users` (`useid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`roles` (
  `rolid` INT(11) NOT NULL AUTO_INCREMENT,
  `rollibelle` TEXT NULL DEFAULT NULL,
  `rolcode` INT(11) NULL DEFAULT NULL,
  `verouillage` INT(11) NULL DEFAULT '0' COMMENT '0 si le droit n\'est pas verouiller et 1 si le droit est verouiller',
  PRIMARY KEY (`rolid`))
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`societe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`societe` (
  `socid` INT(11) NOT NULL AUTO_INCREMENT,
  `socnom` VARCHAR(255) NULL DEFAULT NULL,
  `socabv` VARCHAR(45) NULL DEFAULT NULL,
  `soclogo` TEXT NULL DEFAULT NULL,
  `socville` VARCHAR(45) NULL DEFAULT NULL,
  `socemail` VARCHAR(45) NULL DEFAULT NULL,
  `socregistration` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`socid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`offre_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`offre_detail` (
  `produit` INT(11) NOT NULL,
  `offre` INT(11) NOT NULL,
  `quatite` FLOAT NULL,
  `date` DATETIME NULL,
  `description` TEXT NULL,
  `prixtotal` VARCHAR(45) NULL,
  PRIMARY KEY (`produit`, `offre`),
  INDEX `fk_produits_has_offres_offres1_idx` (`offre` ASC),
  INDEX `fk_produits_has_offres_produits1_idx` (`produit` ASC),
  CONSTRAINT `fk_produits_has_offres_produits1`
    FOREIGN KEY (`produit`)
    REFERENCES `sygeto`.`produits` (`proid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produits_has_offres_offres1`
    FOREIGN KEY (`offre`)
    REFERENCES `sygeto`.`offres` (`offid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sygeto`.`commande_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sygeto`.`commande_detail` (
  `produit` INT(11) NOT NULL,
  `commande` INT(11) NOT NULL,
  `quantite` FLOAT NULL,
  `prixtotal` FLOAT NULL,
  PRIMARY KEY (`produit`, `commande`),
  INDEX `fk_produits_has_commandes_commandes1_idx` (`commande` ASC),
  INDEX `fk_produits_has_commandes_produits1_idx` (`produit` ASC),
  CONSTRAINT `fk_produits_has_commandes_produits1`
    FOREIGN KEY (`produit`)
    REFERENCES `sygeto`.`produits` (`proid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produits_has_commandes_commandes1`
    FOREIGN KEY (`commande`)
    REFERENCES `sygeto`.`commandes` (`cmdid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
